### ISSUE TITLE
Appropriate error type for unable to saveAddressBook after Fees update

### ISSUE THREAD

**Issue by angkoonhwee** [AY2122S1-CS2103T-F13-3/tp#224]
Currently it is throwing a warning in the constructor of LogicManager which I think violates some code quality stuff. It should also be made known to users that if the addressbook is unable to save the data upon fees update they should have a choice to exit the application and retain the previous lastUpdated.

**Comment by Chesterwongz** [comment]
@angkoonhwee any updates on this?

**Comment by angkoonhwee** [comment]
I will change this tomorrow sir
