### ISSUE TITLE
[PE-D] Multiple flags of name only return the latest

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-3/tp#260]
Searching by multiple name flags will only have the latest registered, in contrast with searching by multiple flags of tags. This behaviour does not seem to be documented.

![Screenshot 2021-10-29 at 4.58.12 PM.png](https://raw.githubusercontent.com/zhenghanlee/ped/main/files/17a22917-e490-4034-b2cd-aefa759e6d15.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: zhenghanlee/ped#4

**Comment by lingshanng** [comment]
This can be seen from the command format.
Will add a note to further emphasise
