### ISSUE TITLE
[PE-D] Undoing a delete on a filtered list causes the list to go back to the full list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-3/tp#267]
This issue is similar to the previous issues.

1. Filter the list of students
2. Delete a student from that list. The filter should still remain.
3. Undo the delete command with "undo"
4. The delete command is undone but the list also goes back to the full list and the filter is lost.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: beefham/ped#5

**Comment by lingshanng** [comment]
related to: https://github.com/AY2122S1-CS2103T-F13-3/tp/issues/240

**Comment by angkoonhwee** [comment]
@lingshanng If they insist that this is an error, the add in ModelManager might have to change to disallow this behaviour.
