### ISSUE TITLE
[PE-D] MacOS cmd+Q screen

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-3/tp#270]
Maximise in macOS, then use cmd+Q (for quitting application), the following screen shows (subsequent cmd+Q will render the screen black, but the app still runs and you can't quit it anymore):

![Screenshot 2021-10-29 at 5.14.48 PM.png](https://raw.githubusercontent.com/zhenghanlee/ped/main/files/63e2554a-af33-451e-8fa5-adb6dc1b0261.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: zhenghanlee/ped#7

**Comment by Xiaoyunnn** [comment]
As a mac user, I have not encountered such a problem. @eeliana have you had this prob before?

**Comment by eeliana** [comment]
> As a mac user, I have not encountered such a problem. @eeliana have you had this prob before?

I also have not encountered this problem, both when running in the IDE or using the JAR file.
