### ISSUE TITLE
[PE-D] Cancellation of lessons from dates that have already passed is possible

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F13-3/tp#277]
![image.png](https://raw.githubusercontent.com/lwlshawn/ped/main/files/d2e10743-6a1f-49da-8da0-3bf963590f2f.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: lwlshawn/ped#6

**Comment by eeliana** [comment]
Allowed in the event user forgets to cancel. Fees will have been automatically calculated for this lesson but user has the option to edit the fees accordingly. Will not fix.
