### ISSUE TITLE
UG: Organize command parameters in table

### ISSUE THREAD

**Issue by eeliana** [AY2122S1-CS2103T-F13-3/tp#285]

**Comment by Chesterwongz** [comment]
Like, for each section? or for each command?

**Comment by Chesterwongz** [comment]
Prefix Summary alternative:
https://ay2122s1-cs2103t-w17-1.github.io/tp/UserGuide.html#prefix-summary

![image](https://user-images.githubusercontent.com/70138507/139707597-3c7f5d31-565e-47a0-be44-acd3d7351663.png)

**Comment by Chesterwongz** [comment]
Alternatively, table for each command
![image](https://user-images.githubusercontent.com/70138507/139712965-31cb1774-355b-4904-b7ce-b324d2b57ced.png)

**Comment by eeliana** [comment]
> Like, for each section? or for each command?

Each section since command parameters are largely the same.
There can be another table under ledit describing the extra parameters for cancelled dates.
