### ISSUE TITLE
UG/Help Change optional from square brackets to require with star

### ISSUE THREAD

**Issue by Chesterwongz** [AY2122S1-CS2103T-F13-3/tp#287]
Currently, optional parameters are given by brackets, which can look messy.
We can use star instead to highlight required fields, e.g.,
`add n/NAME* a/ADDRESS* p/PHONE pp/PARENT_PHONE`

**Comment by eeliana** [comment]
I think the * should be put at the front instead because of parameters like `date/dd MMM yyyy`. Would be weird to put at the back
