### ISSUE TITLE
UG: Move notes about command format to the How To Read This Guide section?

### ISSUE THREAD

**Issue by Chesterwongz** [AY2122S1-CS2103T-F13-3/tp#294]

**Comment by eeliana** [comment]
![image](https://user-images.githubusercontent.com/62977276/139791325-fc82f81d-ac9a-4a87-8579-e23ba38d9c14.png)

**Comment by Chesterwongz** [comment]
@eeliana consider highlighting the difference between t/abc t/ and p/123 p/ (the later only takes the last argument)

**Comment by Chesterwongz** [comment]
Also consider #292
