### ISSUE TITLE
Name edit checks

### ISSUE THREAD

**Issue by marcuspeh** [AY2122S1-CS2103T-F13-3/tp#325]
Originally, I have a student named "Marcus"
![image](https://user-images.githubusercontent.com/54053213/140274450-b19bb739-6380-4c1d-9d10-9989583da753.png)

After I did `edit 9 n/Marcus`, a success message is shown. Perhaps, an error message will be better
![image](https://user-images.githubusercontent.com/54053213/140274508-94261742-838e-48cc-899d-dc2f841351aa.png)

**Comment by Chesterwongz** [comment]
will not fix
