### ISSUE TITLE
CalendarFX crashing the app

### ISSUE THREAD

**Issue by marcuspeh** [AY2122S1-CS2103T-F13-3/tp#327]
Not sure what can be done but calendarFx (or whatever yall use for calendar) is slowing down the app by a lot
![image](https://user-images.githubusercontent.com/54053213/140275611-cc77d4a2-63ab-4553-9e37-adeac9245585.png)

This keep happening and the app crashes 
![image](https://user-images.githubusercontent.com/54053213/140275827-8273eca5-aa55-4e22-9bda-113f981b724d.png)

**Comment by eeliana** [comment]
What operations were you doing with the calendar or does your background have a lot of other apps running? I haven't encountered this problem :o @Chesterwongz @lingshanng @Xiaoyunnn @angkoonhwee

**Comment by marcuspeh** [comment]
> What operations were you doing with the calendar or does your background have a lot of other apps running? I haven't encountered this problem :o @Chesterwongz @lingshanng @Xiaoyunnn @angkoonhwee

I created quite a number of recurring classes before this.

**Comment by Chesterwongz** [comment]
could not replicate
