### ISSUE TITLE
BUG: Paying lessons that are equals causes lesson to disappear

### ISSUE THREAD

**Issue by lingshanng** [AY2122S1-CS2103T-F13-3/tp#402]
## Steps to reproduce:
1. Create two lessons with the same date, time range, rates and cancelled, but different outstanding fees.

![image](https://user-images.githubusercontent.com/35279431/140654530-1a60a92d-fb8d-4a2e-9ccb-1e6e7e8e5e86.png)

2. Pay one lesson such that both lessons have the same outstanding fee

Result: the lesson disappears

## Fix:
- Do not use the `Lesson#equals` method in `PaidCommand`
- create empty `TreeSet`. Then remove `toEdit` and add `editedLesson` 

Please follow the implementation of `LessonEditCommand`
- refactor to use `CommandUtil.getPerson`, `CommandUtil.getLesson` 
- instead of a local `createdEditedPerson` method, have a `createUpdatedLessons` method.

**Comment by eeliana** [comment]
I don't think the issue is with using the `Lesson#equals()` method. Is it not because after the edit then the 2 lessons become equal and the set removes the duplicate?

![image](https://user-images.githubusercontent.com/62977276/140655323-a6ebaf58-8e60-412c-b04c-55c8a910c1e1.png)
