### ISSUE TITLE
Increase Test Coverage

### ISSUE THREAD

**Issue by Chesterwongz** [AY2122S1-CS2103T-F13-3/tp#78]
Let's aim for 80%!
Current level: [![codecov](https://codecov.io/gh/AY2122S1-CS2103T-F13-3/tp/branch/master/graph/badge.svg?token=ZHYAC5NIS7)](https://codecov.io/gh/AY2122S1-CS2103T-F13-3/tp)

**Comment by Xiaoyunnn** [comment]
too ambitious
